app:
  id: wx895d89c49c4de3f1
  secret: a253372bb26d847fb22d0c4fb69fc8ba

msg:
  - template:
      id: G7NaPIR1xmflcQ9zsLAedVvqFCs3ZINlyEBSFPJpr2A
      user_id:
          - oil05652esA7qFKzD7hGlovxNmmY
#          - oil0561kgOFYPjn1I_eOshwWn2AA
      other:
        - '101230801'
        - '2023-12-02'
        - '04-22'
